
install:
  - npm install

before_script:
  - |
     export PATH=$HOME/.cargo/bin:$PATH:$PATH &&
     cargo install --git https://github.com/badboy/travis-after-all-rs

language: node_js
node_js:
  - "0.10"
  - "4.0"
  - "4.1"

branches:
  only:
    - master
    - dev

after_success:
  - travis-after-all && curl dev.mateybyrd.net/stats/update